name: helm-upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      version:
        required: true
        description: 'Version of the image to deploy'
        type: string
      helm-values-path:
        description: 'Path to the helm values file'
        type: string
        default: './todoapp/values.yaml'
      helm-release-name:
        type: string
        default: 'todoapp'


jobs:
  deploy-helm:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: helm-package
        path: .

    - uses: actions/download-artifact@v4
      with:
        name: helm-artifacts
        path: .

    - name: Set Up Helm
      uses: azure/setup-helm@v4.2.0

    - uses: azure/setup-kubectl@v4
      name: Set up Kubectl

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}

    - name: Dry Run Helm
      run: |
        helm install --dry-run ${{ inputs.helm-release-name }} ./todoapp-*.tgz  \
        -f ${{ inputs.helm-values-path }} \
        --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
        --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
        --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
        --set todoapp.secrets.SECRET_KEY="${{ secrets.APP_SECRET_KEY }}" \
        --set todoapp.secrets.DB_NAME="${{ secrets.APP_DB_NAME }}" \
        --set todoapp.secrets.DB_USER="${{ secrets.MYSQL_USER }}" \
        --set todoapp.secrets.DB_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
        --set todoapp.secrets.DB_HOST="${{ secrets.APP_DB_HOST }}" \
        --set todoapp.image.tag=${{ github.sha }}

    - name: Deploy Helm to Development
      continue-on-error: true
      run: |
        helm upgrade --install --atomic --wait --timeout 3600s --debug todoapp ./todoapp-*.tgz \
        -f ${{ inputs.helm-values-path }}  \
        --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
        --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
        --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
        --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
        --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
        --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
        --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
        --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
        --set todoapp.image.version=${{ github.sha }}
